version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  python:
    build:
      context: ./python
    container_name: fastapi_bot
    volumes:
      - ./python:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
