version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - backend

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/laravel.sqlite

  fastapi:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: fastapi_bot
    ports:
      - "8002:8002"
    volumes:
      - ./python:/app
    env_file:
      - .env
    command: ["bash", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002"]
    networks:
      - backend

  npm:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "dev"]
    networks:
      - backend

networks:
  backend: